export * from './color-inverter'
export * from './comic-sans-theme'
export * from './placebo-curse'
export * from './variable-reverser'
export * from './indent-switcher'
export * from './emoji-injector'
export * from './sound-effect'
export * from './keyboard-lagger'